### ISSUE TITLE
plugin suddenly unable to play successive episode.

### ISSUE THREAD

**Issue by wrein** [Arias800/plugin.video.vikir#5]
The addon was installed and configured some weeks ago and it was perfectly working until last night. Switching from an episode to another kodi shown an error message.

This is the log:

error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--        
      - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                                                          
      Error Type: <class 'KeyError'>                                                                                                            
      Error Contents: 'main'                                                                                                                    
      Traceback (most recent call last):                                                                                                        
        File "/home/user/.kodi/addons/plugin.video.vikir/addon.py", line 34, in <module>                                                       
            viki.main(sys.argv)                                                                                                                  
        File "/home/user/.kodi/addons/plugin.video.vikir/resources/lib/viki.py", line 54, in main                                              
            check_mode(args)                                                                                                                      
        File "/home/user/.kodi/addons/plugin.video.vikir/resources/lib/viki.py", line 86, in check_mode                                        
            controller.startplayback(args)                                                                                                        
        File "/home/user/.kodi/addons/plugin.video.vikir/resources/lib/controller.py", line 247, in startplayback                                                           
         base64elem = api.request(args, f"videos/{args.episode_id}/drms.json?offline=false&stream_ids={jsonrsp['main'][0]['properties']['track']['stream_id']}&dt=dt3&token={args._auth_token}", None, version=5)
    KeyError: 'main'
                                                                                         
-->End of Python script error report<--

I don't understand if is something related with my kodi installation or it is a specific issue with the plugin.

Kodi is installed on lubuntu on a macmini.

**Comment by wrein** [comment]
It seem related with a dictionary object missing the key main... maybe? I'm not a pythonist...

**Comment by Arias800** [comment]
Hello,
Should be fixed with https://github.com/Arias800/plugin.video.vikir/commit/92dd146a93cf872f50097d658c2c25706b58bbad

**Comment by wrein** [comment]
Hello @Arias800, the fix works like a charm, thank you!

To be precise and to help other people having the same issue, it is necessary to uninstall and reinstall the plugin from scratch (keeping the preferences it's ok) the simple update didn't worked for me, but I think I've perhaps made something wrong.

**Comment by wrein** [comment]
Issue solved.
