### ISSUE TITLE
urllib3 update broke plugin.video.vikir

### ISSUE THREAD

**Issue by w64** [Arias800/plugin.video.vikir#6]
After urllib3 update come to Kodi, plugin.video.vikir doesn't work normally. Can you check what's broken?

**Comment by Australis86** [comment]
At least one of the issues seems to be the DEFAULT_CIPHER line in `service.py`, as the default ciphers were removed in urllib v2.

**Comment by TheScaryX** [comment]
Hello, is it possible to fix it? Thank you very much.

**Comment by Arias800** [comment]
Hello,
It should be fixed in the current master. Please test to ensure that everything works correctly and let me know if it doesn't, as I don't remember why I included these SSL workarounds.

**Comment by TheScaryX** [comment]
It works now, luv you :)
